import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Montserrat } from "next/font/google";
import { Header } from "./_components/Header";
import { Footer } from "./_components/Footer";
import { ThemeProvider } from "next-themes";
import { Suspense } from "react";
import Loading from "./loading";
// import { Loading } from "./loading";
const montserrat = Montserrat({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movie app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem
        disableTransitionOnChange
      >
        <body className={`${montserrat.className}`}>
          <Header />
          <main>
            <Suspense fallback={<Loading />}> {children}</Suspense>
          </main>
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
